### ISSUE TITLE
setState in onToggle doesn't switch without showing an error

### ISSUE THREAD

**Issue by jogee** [PramodJoshi/toggle_switch#11]
When doing a setState() in the onToggle() function, suddenly it doesn't switch to the other value anymore but no error is occurring. Even the state value is switching properly but the view doesn't get updated.

Everything works fine until I try to add some state, what am I doing wrong?

Best regards.

**Comment by PramodJoshi** [comment]
Hi @jogee , could you please provide runnable code and `toggle_switch` version you're currently using?

**Comment by jogee** [comment]
Using version 0.1.8

It occurs with empty setState.

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:toggle_switch/toggle_switch.dart';

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyScreen(),
    );
  }
}

class MyScreen extends StatefulWidget {
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            margin: EdgeInsets.only(top: 30.0),
            child: ToggleSwitch(
                initialLabelIndex: 0,
                labels: ['one', 'two'],
                onToggle: (index) {
                  setState(() {});
                })));
  }
}`

**Comment by PramodJoshi** [comment]
`setState` rebuilds and assigns same `initialLabelIndex` which in your case is '0'. You'll need to assign dynamic index to `initialLabelIndex` when using `setState` as shown below,

```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyScreen(),
    );
  }
}

class MyScreen extends StatefulWidget {
  @override
  _MyScreenState createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  int initialIndex = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
            margin: EdgeInsets.only(top: 30.0),
            child: ToggleSwitch(
                initialLabelIndex: initialIndex,
                labels: ['one', 'two'],
                onToggle: (index) {
                  print('switched index: $index');
                  setState(() {
                    initialIndex = index;
                  });
                })));
  }
}
```

![giphy](https://user-images.githubusercontent.com/17320471/91079132-42eace00-e609-11ea-9caa-7e58355db455.gif)

**Comment by jogee** [comment]
Ah that was the missing piece, many thanks!

**Comment by kcnypmek** [comment]
Is there a possibility to get 2 continuous rows of toggle switches? 
If no,is there a possibility to disable initialIndex (no buttons selected at the start)?

**Comment by faiz-is** [comment]
on tap passing value index from list is that possible ?

**Comment by hillpates123** [comment]
how to set initial  value ,
suppose we want to set second button active.

**Comment by PramodJoshi** [comment]
@hillpates123 code above shows exactly how to do that. Just change `int initialIndex` to **1**.
