### ISSUE TITLE
Change State of toggle

### ISSUE THREAD

**Issue by tajjacob** [PramodJoshi/toggle_switch#15]
What's up bro..
I'm try to change state of toggle.
Somehow the active background color is not working. 
Maybe you can help.

`    onToggle: (index) {
                  print('switched to: $index');
                  setState(() {
                    changeLanguage = index;
                  });
                },`

**Comment by PramodJoshi** [comment]
@tajjacob Hi, i believe this is similar to [11](https://github.com/PramodJoshi/toggle_switch/issues/11). Could you please take a look and see if the example i provided resolves your issue? If not, please provide a runnable code so that i can test on my end.

**Comment by tajjacob** [comment]
Thanks brother! it works like a charm! God bless you!

**Comment by PramodJoshi** [comment]
Great!
