### ISSUE TITLE
Toggle don't work when setstate call in toggle callback

### ISSUE THREAD

**Issue by didierboka** [PramodJoshi/toggle_switch#19]
When try to change dynamically a widget state (ex: Visibility status)  and try to call setstate function in toggle callback,  the widget Visibility status work fine but toggle not change color.

**Comment by Work90210** [comment]
@didierboka How was this fixed?

**Comment by zigoval** [comment]
https://github.com/PramodJoshi/toggle_switch/issues/11

It's not a bug, more like... missing documentation :) 
                  ToggleSwitch(
                    initialLabelIndex: level,
                    activeBgColor: Colors.deepPurpleAccent,
                    minWidth: 100,
                    labels: [
                      'Niveau 1',
                      "Niveau 2",
                    ],
                    onToggle: (index) {
                      setState(() {
                        level = index;
                      });
                    },
                  )

**Comment by didierboka** [comment]
It fixed ! Thanks you !
*Serges Didier BOKA* *| Android Apps Developer*
Abidjan - Côte d'Ivoire
Tel. : 57 18 79 63
e-mail : *didierboka1@gmail.com <didierboka1@gmail.com>*
