### ISSUE TITLE
animated transition

### ISSUE THREAD

**Issue by ancileddu** [PramodJoshi/toggle_switch#20]
hi all, is it possible to have an animated transition when change from a button to another? thanks

**Comment by PramodJoshi** [comment]
Hi, it's not possible at the moment but i'll take a look. Do you have an example?

**Comment by rmControls** [comment]
Yep, I also looking this feature....

**Comment by PramodJoshi** [comment]
@ancileddu @rmControls good news! basic animation is now available in `toggle_switch: ^1.0.0+1`. 

**Default animation:**
```dart
animate: true
```

**Custom animation:**
```dart
animate: true
curve: Curves. bounceIn
```

Also, please check examples for more info. 

Cheers!
