### ISSUE TITLE
Cannot use setState in onToggle

### ISSUE THREAD

**Issue by frozencodeuz** [PramodJoshi/toggle_switch#21]
I wanted to use setState with toggle switch setState is working fine but toggle not changing any solution for this?

**Comment by PramodJoshi** [comment]
@frozencodeuz Hi, i believe this is similar to [11](https://github.com/PramodJoshi/toggle_switch/issues/11). Could you please take a look and see if the example i provided resolves your issue? If not, please provide a runnable code so that i can test on my end.
