### ISSUE TITLE
Long labels showing only some letters

### ISSUE THREAD

**Issue by nbnD** [PramodJoshi/toggle_switch#22]

**Comment by PramodJoshi** [comment]
@nbnD toggle_switch is designed for short text options. It wraps text to prevent the overflow and maintain consistency. You can try increasing your `minWidth` and depending on your device size and available width space, it should display more/all characters.

**Comment by PhilipPurwoko** [comment]
Should provide overflow customization. For example if I want to make it `overflow.clip` instead of elipsis (default)

**Comment by PramodJoshi** [comment]
@PhilipPurwoko good idea. I'll make this a part of `customTextStyles` and add it to the next version.
