### ISSUE TITLE
Toggle On Left Not Changing BgColor in 1 click ?

### ISSUE THREAD

**Issue by DEEPJYOTSINGHKAPOOR** [PramodJoshi/toggle_switch#25]

**Comment by PramodJoshi** [comment]
@DEEPJYOTSINGHKAPOOR Could you please provide a runnable code so that i can create the issue on my end? Also, this could be similar to [11](https://github.com/PramodJoshi/toggle_switch/issues/11) but i'd know more when i see your code.

**Comment by DEEPJYOTSINGHKAPOOR** [comment]
Thanks, its the same issue.
