### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vegeta-ssaiyan** [PramodJoshi/toggle_switch#27]
Hi Pramod, thanks for creating this!

Just a qtn, can we decide the number of rows?

Context: I have 2 rows of options for users to choose from. I could do a separate toggle switch for 2 created rows, but I reckon it would be harder to store the printed value as I want them to choose only one choice. 

it would be better if the toggle switch could allow 2 rows in the same widget and they just choose one option and that option is captured.

Maybe this feature is already out. >.<, and is staring me in the face.
Any guidance is appreciated.

Cheers!

**Comment by vegeta-ssaiyan** [comment]
Also Pramod, is there a way to change the margins between the options? I've placed the whole widget in a constraint box to limit its size, but the content still overflows, was thinking of changing the margins but idt there's this option available.

**Comment by PramodJoshi** [comment]
Hi @vegeta-ssaiyan , unfortunately, it's not possible to create two rows or change margins atm. I'm currently working on multiple rows feature. Regarding overflow issue, it should automatically resize to prevent overflows based on your device width and you shouldn't need additional constraint box. Could you please post a screenshot and basic runnable code to create the issue?

**Comment by vegeta-ssaiyan** [comment]
Thank you Pramod, all good now, no worries!
