### ISSUE TITLE
Make icons optional

### ISSUE THREAD

**Issue by FRANIAZA** [PramodJoshi/toggle_switch#28]
Hi, I am trying to create a 3-switch-button. All three switches have labels. I would like to have icons on the first and last witch, but not on the middle one. 
It seems that currently this cannot be achieved. It would be a very nice enhancement :)

**Comment by PramodJoshi** [comment]
@FRANIAZA great suggestion! This is now available in `toggle_switch: ^1.1.0` . You can just pass in `null` where you don't want to display icon e.g. `icons: [Icons.add, null, Icons.remove]` . Also, please check examples for more info. Cheers!
