### ISSUE TITLE
(radiusStyle: false) does not work when textDirection is set to TextDirection.rtl

### ISSUE THREAD

**Issue by ali-1989** [PramodJoshi/toggle_switch#30]
Hello,
I upgraded to the new version, in the new version all the buttons are rounded at the borders.
radiusStyle: false has no effect !!

I mean the connection border between the two buttons. Not like before.
![d8d18130-d5a2-42b9-af18-a2b552f7bd35](https://user-images.githubusercontent.com/30122089/123914070-3c995100-d994-11eb-9e92-83efbf44372a.png)

**Comment by PramodJoshi** [comment]
@ali-1989, i was unable to reproduce this issue with 1.2.0. Could you please post a minimum runnable code to reproduce this? Also, just to confirm few things, please post toggle_switch version you're using as well as flutter doctor -v.

**Comment by ali-1989** [comment]
Hi,

I use : toggle_switch: ^1.2.0 


flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.10240], locale fa-IR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0r4)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (1 available)

• No issues found!
-----------------------------------------------------
```
ToggleSwitch(
                  initialLabelIndex: state.selectedGender,
                  cornerRadius: 12.0,
                  radiusStyle: false,
                  activeBgColor: [AppThemes.currentTheme.activeItemColor],
                  activeFgColor: Colors.white,
                  totalSwitches: 2,
                  inactiveBgColor: AppThemes.currentTheme.inactiveBackColor,
                  inactiveFgColor: AppThemes.currentTheme.inactiveTextColor,
                  labels: ['male', 'female'],
                  onToggle: (index) {
                    ...
                  },
                ),
```

**Comment by PramodJoshi** [comment]
Hi @ali-1989 , unfortunately, i'm still unable to reproduce this issue. Seems to be working fine as expected. Here's my test video,

[![Test video](https://user-images.githubusercontent.com/17320471/124392847-2c97af00-dcbd-11eb-9920-7739e6dbe45e.png)](https://drive.google.com/file/d/1ThOMOtQgnTtpoo18QP8q8vOamRKHRlkb/view?usp=sharing "Test Video")

You can try few things:
- flutter clean
- `radiusStyle` is false by default so you don't need to pass this param if you're not setting it to true. Try removing `radiusStyle`.

Let's leave this issue open for now to see if anyone else experiences similar behavior.

**Comment by ali-1989** [comment]
Hi again.
I realized that in `TextDirection.rtl `mode 
 This happens.

if i set TextDirection.ltr that is ok, but on TextDirection.rtl mode is not.

**Comment by PramodJoshi** [comment]
Could you please post a complete runnable code to reproduce this issue?

**Comment by ali-1989** [comment]
issue if:

```
Directionality(
  textDirection: TextDirection.rtl
  child: ToggleSwitch(
          initialLabelIndex: state.selectedGender,
          cornerRadius: 12.0,
          radiusStyle: false,
          activeBgColor: [AppThemes.currentTheme.activeItemColor],
          activeFgColor: Colors.white,
          totalSwitches: 2,
          inactiveBgColor: AppThemes.currentTheme.inactiveBackColor,
          inactiveFgColor: AppThemes.currentTheme.inactiveTextColor,
          labels: ['male', 'female'],
          onToggle: (index) {
            ...
          },
        ),
  )
```

**Comment by ali-1989** [comment]
My friend, do not you want to solve this problem?

**Comment by PramodJoshi** [comment]
@ali-1989 Apologies for the delay. I think i know what's causing this issue and i'm trying to find an elegant way to resolve this. I'll keep you posted.

**Comment by PramodJoshi** [comment]
Hi, i've added a fix to resolve this. Please use the latest version `toggle_switch: ^1.4.0` and set `textDirectionRTL: true`. Also, please check the example with explanation in README. Cheers!

**Comment by ali-1989** [comment]
Hi, Thanks. yes in new version  it is solved.
