### ISSUE TITLE
toogle shitch is not loading properly

### ISSUE THREAD

**Issue by akashlilhare** [PramodJoshi/toggle_switch#31]
I am using the example code but getting this strange effect. Currently, I using this version  toggle_switch: ^1.2.0

` ToggleSwitch(
              minWidth: 90.0,

              initialLabelIndex: 1,
              cornerRadius: 20.0,
              activeFgColor: Colors.white,
              inactiveBgColor: Colors.grey,
              inactiveFgColor: Colors.white,
              totalSwitches: 2,
              labels: ['Male', 'Female'],
         
              activeBgColors: [[Colors.blue],[Colors.pink]],
              onToggle: (index) {
                print('switched to: $index');
              },
            ),`

![sample](https://user-images.githubusercontent.com/39927872/124403030-995c8900-dd51-11eb-8863-f6c5c848d40a.gif)

**Comment by PramodJoshi** [comment]
Hi @akashlilhare , please post a complete runnable code (not just ToggleSwitch portion) so that i can recreate this issue. 

This could be due to your parent widget that's enclosing ToggleSwitch.

**Comment by akashlilhare** [comment]
I am using this as a separate widget and calling it inside ListView. After updating with the latest version of the package I am facing this issue. Previously it was working fine.

```
    import 'package:flutter/material.dart';
    import 'package:toggle_switch/toggle_switch.dart';

    class Test extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return ToggleSwitch(
          initialLabelIndex: 0,
          cornerRadius: 20.0,
          activeFgColor: Colors.white,
          inactiveBgColor: Colors.grey,
          inactiveFgColor: Colors.white,
          totalSwitches: 2,
          labels: ['Cm', 'Feet'],
          activeBgColors: [
            [Colors.blue.shade700],
            [Colors.blue.shade700]
          ],
          onToggle: (index) {},
        );
      }}
```

```
    ListView(
        children: [
        Padding(
            padding: const EdgeInsets.symmetric(horizontal: 28.0),
            child: Test(),
          ),],
      ),
```





this is the output for the above code

![Screenshot_20210705-224307 (1)](https://user-images.githubusercontent.com/39927872/124506520-71206900-dde9-11eb-9846-4d01083bb443.png)

**Comment by PramodJoshi** [comment]
All child widgets are expanded by default in `ListView` (not just `ToggleSwitch`). To fix this, you can simply enclose your child widget in ListView with `Align` like so,

```dart
ListView(
            children: [
              Align(
                alignment: Alignment.center,
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 28.0),
                  child: Test(),
                ),
              ),
            ],
          ),
```

**Comment by akashlilhare** [comment]
That was a silly mistake from my side. Thanks for cooperating with me.
