### ISSUE TITLE
Allow custom animation duration

### ISSUE THREAD

**Issue by QuentinSc** [PramodJoshi/toggle_switch#32]
Hello,

Thank you for your work.
Why there is no parameter to customize the animation duration ?
https://github.com/PramodJoshi/toggle_switch/blob/8f5c80bed5fd815507cdb83922bd3d0ea3aba3a1/lib/toggle_switch.dart#L298

**Comment by PramodJoshi** [comment]
Hi, the idea was to keep it simple but seems like making it customizable would make more sense. I'll add this in the next release. Cheers.

**Comment by PramodJoshi** [comment]
This has been added to v1.3.0. Cheers!
