### ISSUE TITLE
Switches not working properly

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [PramodJoshi/toggle_switch#36]
**Describe the bug**
The toggle button does not switch if changed two times before.

**To Reproduce**
`ToggleSwitch(
              animate: true,
              changeOnTap: !isPaymentMethodAdded,
              totalSwitches: 2,
              activeBgColor: const [whiteblueColor],
              inactiveFgColor: Colors.white,
              minWidth: screenSize.width * .3,
              labels: const ["PalPal", "Card"],
              onToggle: (index) {
               
              },
            ),`

**Expected behavior**
The toggle should be properly switched all the time when it is changed

**Additional information**
- `toggle_switch: ^1.2.0` version

**Comment by PramodJoshi** [comment]
Hi, please provide a complete/minimum runnable code. I won't be able to debug with just the ToggleSwitch portion above. Also, this sounds like [issue 11](https://github.com/PramodJoshi/toggle_switch/issues/11#issuecomment-679277018) which i have included in README. Please check it out if you haven't already and let me know if that fixes the issue.

**Comment by UmairSaqibBhutta** [comment]
Yes, the issue is the same as for issue 11 for I am closing it.
Thanks for support.
