### ISSUE TITLE
Not able to set null to initialLabelIndex 

### ISSUE THREAD

**Issue by Hiteshc29** [PramodJoshi/toggle_switch#37]
Need to set null at initialLabelIndex so that at initial none option is selected

**Comment by PramodJoshi** [comment]
I'll add this in the next version. Thanks for bringing it up.

**Comment by itaishalom** [comment]
@PramodJoshi Done. Please take a look. When do we expect the new release?

**Comment by PramodJoshi** [comment]
This has been added to v1.3.0. Cheers!
