### ISSUE TITLE
Different width of each switch.

### ISSUE THREAD

**Issue by Shashwat-111** [PramodJoshi/toggle_switch#38]
Not able to give different width to each button. My tabs name are like "SMS", "Clarification", "Feedback"...but SMS text take up the same space as Clarification, which I don't want

**Comment by westekim** [comment]
This would be great! Using it for a case where the options are "No", "?", "Yes" (in different languages so might be longer than 3 letters), with the default being the "?". Having the "?" being more narrow would be nice.

**Comment by PramodJoshi** [comment]
@Shashwat-111 @westekim this is now available in `toggle_switch: ^1.4.0` . Cheers!

**Comment by westekim** [comment]
Perfect! Thanks!
And confirmed that it does work exactly as I wanted it to.
