### ISSUE TITLE
Cannot create switch without labels

### ISSUE THREAD

**Issue by Tushar-OP** [PramodJoshi/toggle_switch#4]
Whenever the labels is null, it throws an error saying 

`
The getter 'length' was called on null.
Receiver: null
Tried calling: length
`

I only want icons in the switch

**Comment by PramodJoshi** [comment]
@Tushar-OP You should be able to achieve that with `labels: ['', '']` for now (screenshot below). I'll try to add a check in next version.

<img width="326" alt="Screen Shot 2020-07-18 at 2 50 46 PM" src="https://user-images.githubusercontent.com/17320471/87860818-2373cd80-c906-11ea-9dcd-4972d7522d8c.png">
