### ISSUE TITLE
My toggleSwitch doesn't switch and my setstate doesn't work

### ISSUE THREAD

**Issue by LucaSappey** [PramodJoshi/toggle_switch#46]
**Describe the bug**
When I click on the ToggleSwitch, nothing switch, but my index are good when I print it

**To Reproduce**
```
Column(children: [
        ToggleSwitch(
          minWidth: 100.0,
          initialLabelIndex: showIOSQrcode,
          totalSwitches: 2,
          labels: ['Apple Store', 'Play Store'],
          onToggle: (index) {
            print('switched index: $index');
            setState(() {
              showIOSQrcode = index;
            });
            print(showIOSQrcode);
          },
        ),
        Padding(padding: EdgeInsets.symmetric(vertical: 5)),
        showIOSQrcode == 0
            ? Image(
                image: AssetImage(
                    'assets/images/qrcode_ios.png'),
                width: 180,
              )
            : Image(
                image: AssetImage(
                    'assets/images/qr_code_play_store.png'))
        ]),
```
**Expected behavior**
I expected to see the switch between Apple and Play Store and to see the image change with it

**Additional information**

 toggle_switch: ^1.3.0

[✓] Flutter (Channel unknown, 2.0.6, on macOS 12.0.1 21A559 darwin-arm, locale fr-FR)
    • Flutter version 2.0.6 at /Users/lucas/Development/flutter
    • Framework revision 1d9032c7e1 (7 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lucas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • iPhone Lucas (mobile) • baaa60cd2019dbd8bd0c781818b0fa03815e65c2 • ios            • iOS 15.0.2
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

**Comment by Saddi993** [comment]
toggle will fire event on every click ... i have handle this condition by below code

```
onToggle: (index) async {
    print('switched to: $index');
    if (index == 1) {
    context.setLocale(Locale('ur'));
    } else {
    context.setLocale(Locale('en'));
    }
    Navigator.pop(context);
}`
```

**Comment by PramodJoshi** [comment]
@LucaSappey please check **setState inside toggle** example in README.  Let me know if that fixes the issue.

**Comment by LucaSappey** [comment]
Sorry guys that was on me. I initialized my boolean (showQrCode) in my build method. Now that I did it outside, this is working.
Thank you very much for your answers <3
