### ISSUE TITLE
Is there a way to center labels?

### ISSUE THREAD

**Issue by MauroDiamantino** [PramodJoshi/toggle_switch#47]
Hi, I would like to center labels in a toogle_switch widget, but I haven't found a parameter to do that. Is there a way to do what I want?

Maybe if parameter `labels` type is changed from `List<String>` to `List<Text>`, it would be possible to center the labels. What do you think?

**Comment by PramodJoshi** [comment]
@MauroDiamantino labels should be centered by default as shown in the examples.
