### ISSUE TITLE
transparent inactiveBgColor with colored border

### ISSUE THREAD

**Issue by brandoneedyou** [PramodJoshi/toggle_switch#48]
Just try the code below:

ToggleSwitch(
            initialLabelIndex: 0,
            totalSwitches: 3,
            borderWidth: 1,
            borderColor: const [Colors.white],
            labels: const ['aaa', 'bbb', 'ccc'],
            activeBgColor: const [Colors.white],
            activeFgColor: const Color(0xfff11fab),
            inactiveBgColor: Colors.transparent,
            inactiveFgColor: Colors.white,
            onToggle: (index) {},
          ),

inactiveBgColor will be covered by borderColor. How to solve this? 😲

toggle_switch version 1.3.0

**Comment by PramodJoshi** [comment]
@brandoneedyou Sorry for the delayed response. Seems like all your primary colors are white as well as inactiveBgColor is transparent. I'd suggest using darker inactiveBgColor (e.g. Colors.blueGrey) to make your widget element visible as shown in the screenshot below.

<img width="270" alt="Screen Shot 2022-01-22 at 12 08 20 PM" src="https://user-images.githubusercontent.com/17320471/150648527-3c34d1cf-d76b-41c2-8cb8-a1581a3ff03a.png">
