### ISSUE TITLE
Border around toggle?

### ISSUE THREAD

**Issue by itaishalom** [PramodJoshi/toggle_switch#49]
Hi, do you think that a border around the selected side of the toggle only, is possible?

**Comment by PramodJoshi** [comment]
Hi Itai, I think that's a great idea and should be possible. I'll look into it as soon as i get chance. Thanks.

**Comment by itaishalom** [comment]
You want me to PR you? Maybe I'll get to it first.

**Comment by PramodJoshi** [comment]
Sure, that'd be great. Thanks!

**Comment by itaishalom** [comment]
Done it. Can you check my PR @PramodJoshi ?

**Comment by itaishalom** [comment]
Any chance of pub dev release soon?

**Comment by PramodJoshi** [comment]
Available in `toggle_switch: ^2.0.1`

**Comment by itaishalom** [comment]
ohhhh Thank you!
