### ISSUE TITLE
How To Customized TextStyle

### ISSUE THREAD

**Issue by AravinthSri** [PramodJoshi/toggle_switch#5]
Kindly guide me to update textstyle.

**Comment by PramodJoshi** [comment]
@AravinthSri You can use `activeFgColor` and `inactiveFgColor` to change the text color and `fontSize` to change the text size but other stylings are not possible at the moment. I'm currently working on this and will be available soon. The idea was to make this widget as simple as possible.

**Comment by PramodJoshi** [comment]
@AravinthSri  Good news! `customTextStyles:` option is now available in `toggle_switch: ^1.1.0` . Please check examples for more info. Cheers!

**Comment by AliPunjabi** [comment]
I think inactiveFgColor will not works if we use customTextStyle, am I right?, Its is clear from your example as well as I checked it by my ownself, inactivefgcolor is not working.

**Comment by PramodJoshi** [comment]
@AliPunjabi correct. inactiveFgColor is ignored when using customTextStyle
