### ISSUE TITLE
do not limit the maximum width

### ISSUE THREAD

**Issue by foraixh** [PramodJoshi/toggle_switch#50]
Have you thought about not limiting the maximum width? Allow user to customize width with horizontal swipe view? Because as an individual developer, sometimes it is hard to replace text with icons, which will cause the text to automatically collapse, which is silly. Thank you very much if you can.
![image](https://user-images.githubusercontent.com/39892450/151284344-8de50940-ca09-48ac-b68b-30f122e02bdf.png)

**Comment by PramodJoshi** [comment]
@foraixh you should now be able to use customWidths without restriction in `toggle_switch: ^2.0.1` . Cheers!
