### ISSUE TITLE
setState  function doesnot work with the toggle

### ISSUE THREAD

**Issue by Joezzy** [PramodJoshi/toggle_switch#56]
**Describe the bug**
Sample code

```
ToggleSwitch(
                  minWidth: double.infinity,
                  minHeight: MySize.size40,
                  fontSize: 16.0,
                  initialLabelIndex: 0,
                  activeBgColor: [AppTheme.ovaOrange],
                  activeFgColor: Colors.white,
                  inactiveBgColor: AppTheme.ovaGrey,
                  inactiveFgColor: Colors.grey[900],
                  totalSwitches: 2,
                  labels: ['Orders', 'WIP'],
                  onToggle: (index) {
                    print('switched to: $index');
                    setState(() {
                      if(index==0)
                        showOrder=true;
                      else
                        showOrder=false;

                    });                  },
                )

```
the right index is printed but the Active color doesnot change

**Comment by tickets14** [comment]
I'm also experiencing this bug.

**Comment by Joezzy** [comment]
> I'm also experiencing this bug. Did you manage to solve this?

create an "int" variable  and save the selected index in it. 

say:

int selectedIndex=0;


ToggleSwitch(
                  minWidth: double.infinity,
                  minHeight: MySize.size40,
                  fontSize: 16.0,
                  initialLabelIndex: selectedIndex,
                  activeBgColor: [AppTheme.ovaOrange],
                  activeFgColor: Colors.white,
                  inactiveBgColor: AppTheme.ovaGrey,
                  inactiveFgColor: Colors.grey[900],
                  totalSwitches: 2,
                  labels: ['Orders', 'WIP'],
                  onToggle: (index) {
                    print('switched to: $index');
                    setState(() {
                  
selectedIndex=index;
                    });                  },
                )

**Comment by nathantew14** [comment]
> > I'm also experiencing this bug. Did you manage to solve this?
> 
> create an "int" variable and save the selected index in it.
> 
> say:
> 
> ```
> 
> int selectedIndex=0;
> 
> 
> ToggleSwitch(
>                   minWidth: double.infinity,
>                   minHeight: MySize.size40,
>                   fontSize: 16.0,
>                   initialLabelIndex: selectedIndex,
>                   activeBgColor: [AppTheme.ovaOrange],
>                   activeFgColor: Colors.white,
>                   inactiveBgColor: AppTheme.ovaGrey,
>                   inactiveFgColor: Colors.grey[900],
>                   totalSwitches: 2,
>                   labels: ['Orders', 'WIP'],
>                   onToggle: (index) {
>                     print('switched to: $index');
>                     setState(() {
>                   
>                              selectedIndex=index;
>                     });                  },
>                 )
> ```

This is a nice workaround, thanks. I feel like this should be considered a bug though. Makes no sense for `setState` to reset the selected index to the initial index.

**Comment by PramodJoshi** [comment]
Anyone experiencing this issue, please read **setState() inside onToggle** portion of the README.
