### ISSUE TITLE
Switch not displayed when only one border side is desired (activeBorders)

### ISSUE THREAD

**Issue by alvarosantisteban** [PramodJoshi/toggle_switch#57]
**Describe the bug**
Borders seem to be only displayed when the four sides of it are not `BorderSide.none`. Not only that, but they need to have the same width and color.

**To Reproduce**

// This works
`activeBorders: [Border(bottom: BorderSide(width: 16.0, color: Colors.purple), right: BorderSide(width: 16, color: Colors.purple), left: BorderSide(width: 16.0, color: Colors.purple), top: BorderSide(width: 16.0, color: Colors.purple))], `

// This doesn't work
`activeBorders: [Border(bottom: BorderSide(width: 16.0, color: Colors.red), right: BorderSide(width: 16, color: Colors.purple), left: BorderSide(width: 16.0, color: Colors.purple), top: BorderSide(width: 16.0, color: Colors.purple))],`

// This doesn't work neither
`activeBorders: [Border(bottom: BorderSide(width: 16.0, color: Colors.red))],`

**Expected behavior**
For this case 
`activeBorders: [Border(bottom: BorderSide(width: 16.0, color: Colors.red))],`
I would expect a border to be displayed at the bottom.

Since the ToggleSwitch class doesn't have a decoration parameter, it's not possible to add a border at the bottom in any other way.

**Additional information**
- `toggle_switch` version  ^2.0.1

**Comment by PramodJoshi** [comment]
Hi @alvarosantisteban, sorry for the delayed response. I'll take a look and get back to you.

**Comment by PramodJoshi** [comment]
@alvarosantisteban Seems like this is a [Flutter bug](https://github.com/flutter/flutter/issues/12583). I'll try to investigate this further for workarounds. Closing for now.
