### ISSUE TITLE
Safari (I can't toggle on Safari)

### ISSUE THREAD

**Issue by nathanblanchard12** [PramodJoshi/toggle_switch#60]
**Describe the bug**

**To Reproduce**
Complete runnable code to reproduce the bug/issue.

**Expected behavior**

**Screenshots**

**Additional information**
- `toggle_switch` version
- `flutter doctor -v`
- Any other additional information.

**Comment by nathanblanchard12** [comment]
I am using toggle version ^1.3.0.

**Comment by PramodJoshi** [comment]
Hi @nathanblanchard12, please try the latest version - `toggle_switch: ^2.0.1`. Post a complete runnable code if you still experience the issue.

**Comment by PramodJoshi** [comment]
@nathanblanchard12 I tested the latest version `toggle_switch: ^2.0.1` on Safari and everything seems to be working fine. Closing this.

Safari version - 16.3 (18614.4.6.1.6)

![Screen recording](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2RlMjAzMjdhNTI5N2M0Yzg5NDM5NmI2NDUyZTFjOTA1OTRlY2NmMSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/gIL8BXZRb7zcQZdAm9/giphy.gif)
