### ISSUE TITLE
Allow RichTitle or Widget for labels

### ISSUE THREAD

**Issue by baptistesx** [PramodJoshi/toggle_switch#61]
Hi!

I need to implement this design: 
![image](https://user-images.githubusercontent.com/9638281/174548945-2602a874-72de-4e7b-a649-db6a40b761ce.png)

I think with the current lib, I cannot right? Maybe allowing a List<Widget> for tabs or at least List<RichText> might get the trick done, what do you think?

Also maybe I should create a new issue about the possibility of disableling a tab (see my screenshot)?

Thanks :)

**Comment by PramodJoshi** [comment]
Hi @baptistesx, that's right. The current version of toggle_switch does not support subtitles but I'm currently exploring some options to add custom widgets.

Regarding the option to disable a switch, please create a new issue with a short description and label it as an enhancement.

**Comment by sagarappscrip** [comment]
There should be the option to add widget List<Widget> in place of List<icons>.

**Comment by PramodJoshi** [comment]
@baptistesx  @sagarappscrip `customWidgets` is now available in the latest version. Cheers!
