### ISSUE TITLE
How to add TextField between two switches?

### ISSUE THREAD

**Issue by PavelTurk** [PramodJoshi/toggle_switch#62]
I need to do the following: 

![Screenshot from 2022-07-25 20-59-55](https://user-images.githubusercontent.com/10261361/180843712-90762ae6-a72f-4411-95a6-37a2bf17a879.png)

By other words only one of two switches can be selected and there must be a TextField between them. Can it be done with toggle_switch? If yes, could anyone show how to do it?

**Comment by PramodJoshi** [comment]
Hi @PashaTurok, this is not possible with toggle_switch. I'm assuming you're trying to increase or decrease the TextField value when you tap the '-' or '+' button. I'd suggest using a Row of regular buttons and TextField for this.
