### ISSUE TITLE
Allow disable tab

### ISSUE THREAD

**Issue by baptistesx** [PramodJoshi/toggle_switch#63]
It would be nice to be able to disable a switch value like this:

![image](https://user-images.githubusercontent.com/9638281/182954511-5ba1ee96-8846-4e5e-bfe1-49bc01835d38.png)

**Comment by mehulsharma15** [comment]
Do we have this feature added ??

**Comment by rohitbhoite** [comment]
https://github.com/PramodJoshi/toggle_switch/pulls

Did a fix in this PR.

**Comment by PramodJoshi** [comment]
Thanks @rohitbhoite ! 

@baptistesx please use the latest version
