### ISSUE TITLE
Allow Custom Font Style but still respect activeFgColor and inactiveFgColor

### ISSUE THREAD

**Issue by ryanheitner** [PramodJoshi/toggle_switch#64]
**Is your feature request related to a problem? Please describe.**
I would like a custom font that changes color on active and inactive.

**Describe the solution you'd like**
              textStyle = widget.customTextStyles!.length == 1
                      ? widget.customTextStyles![0]!
                      : (widget.customTextStyles!.length > index ~/ 2 &&
                              widget.customTextStyles![index ~/ 2] != null
                          ? widget.customTextStyles![index ~/ 2]!
                          : defaultTextStyle);

           change requested:
                  if (active && activeFgColor != null) {
                    textStyle = textStyle.copyWith(color: activeFgColor);
                  } else if (!active && inactiveFgColor != null) {
                    textStyle = textStyle.copyWith(color: inactiveFgColor);
                  }

**Describe alternatives you've considered**

**Additional context**

**Comment by Aljnk** [comment]
Same request - very important thing as for me.

**Comment by mohabmm** [comment]
#74 Solved here

**Comment by PramodJoshi** [comment]
@ryanheitner @Aljnk  If I understand your request correctly and if I'm not mistaken, this is already available in the current version `2..0.1`. Custom text style should automatically take in your `activeFgColor` and `inactiveFgColor`. You don't need to pass `color` with your custom text style.

**Comment by PramodJoshi** [comment]
Available in `toggle_switch: ^2.1.0` . Cheers!
