### ISSUE TITLE
Allow intialValueIndex to be null

### ISSUE THREAD

**Issue by vasilich6107** [PramodJoshi/toggle_switch#67]
Hi @PramodJoshi 
Thanks for your package

**Is your feature request related to a problem? Please describe.**
There is no way to make switch unselected when displaying empty form

**Describe the solution you'd like**
Allow to set `intialValueIndex` to `null`

**Describe alternatives you've considered**
No alternatives for now.

**Additional context**
no

**Comment by PramodJoshi** [comment]
Hi @vasilich6107 , this is already available. Please check the README example titled **With custom text styles, null initial label, double tap to de-activate** .
