### ISSUE TITLE
Last switch item is always stretched to full width inside CustomScrollView

### ISSUE THREAD

**Issue by khoadng** [PramodJoshi/toggle_switch#70]
**Describe the bug**
When used inside `CustomScrollView`, last item in the switch always expand to full width. 

**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:toggle_switch/toggle_switch.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverPadding(
              padding: const EdgeInsets.only(top: 100),
              sliver: SliverToBoxAdapter(
                child: ToggleSwitch(
                  labels: const ['America', 'Canada', 'Mexico'],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

**Expected behavior**
It shouldn't stretch the last item

**Screenshots**

![simulator_screenshot_BE797BAD-61FA-44B2-92C1-677AE93A17F1](https://user-images.githubusercontent.com/19619099/199783844-ad84e4d6-226c-4a8d-91c0-14f28837a0d7.png)

**Additional information**
- `toggle_switch` version 2.0.1

**Comment by khoadng** [comment]
Wrapping `ToggleSwitch` inside `Center` somehow fixed it. 

I don't know if the above solution is an intended behavior or just a workaround so I will keep this issue open.

**Comment by PramodJoshi** [comment]
@khoadng Sorry for the delay. It seems like this is a sliver widget behavior that causes child widgets to expand to device width. You can also re-create this with a simple container (code below),

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverPadding(
              padding: const EdgeInsets.only(top: 100),
              sliver: SliverToBoxAdapter(
                child: Container(
                  width: 80.0,
                  color: Colors.blue,
                  child: Text('Test'),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

Screenshot:
<img width="468" alt="Screenshot 2023-04-25 at 4 43 46 PM" src="https://user-images.githubusercontent.com/17320471/234411042-1d21480f-ba55-4896-b4fc-3da152917947.png">


Closing this. 

**### Anyone experiencing this behavior, please wrap `toggle_switch` with `Center`**
