### ISSUE TITLE
how to change  textstyle of active toggle  ?

### ISSUE THREAD

**Issue by ankitdifferenzsystem** [PramodJoshi/toggle_switch#86]
**Describe the bug**

**To Reproduce**
Complete runnable code to reproduce the bug/issue.

**Expected behavior**

**Screenshots**

**Additional information**
- `toggle_switch` version
- `flutter doctor -v`
- Any other additional information.

**Comment by PramodJoshi** [comment]
Create a default textstyle and use `setState` in `onToggle` to change the style. Please check readme and examples in closed issues.
