### ISSUE TITLE
padding of icons

### ISSUE THREAD

**Issue by FiifiB** [PramodJoshi/toggle_switch#9]
There seems to be no padding of the icons so they are very close to the edge. See image attached

![image](https://user-images.githubusercontent.com/4690372/89668455-c25b6c00-d8ab-11ea-8e3b-c0c77fc67ce5.png)

**Comment by PramodJoshi** [comment]
@FiifiB Good catch, thank you for reporting. This is now fixed in [db9bd83](https://github.com/PramodJoshi/toggle_switch/commit/db9bd836b2b1edd4848f83d7051f967d2364221a).
