### ISSUE TITLE
customWidths is not working.

### ISSUE THREAD

**Issue by kwang87** [PramodJoshi/toggle_switch#91]
**Describe the bug**
after flutter update, customWidths is not working.

**To Reproduce**
customWidths: const [50, 55, 90, 50],

**Expected behavior**
It should be displayed on the screen according to the set size, but a strange blank space is left on the right.

**Screenshots**
![image](https://github.com/PramodJoshi/toggle_switch/assets/44594502/cfa838e1-8915-486a-800c-b45b7686141d)

**Comment by PramodJoshi** [comment]
@kwang87 Could you please provide a complete, runnable, and reproducible code sample?
