### ISSUE TITLE
Allow the widget to expands to fit its parent

### ISSUE THREAD

**Issue by matteoberla** [PramodJoshi/toggle_switch#92]
HI, i've tyed by wrapping the widget with an Expanded but i can't reach the final result.

I would like the widget to expands to fit the entire parent width, is it possible?

**Comment by PramodJoshi** [comment]
HI @matteoberla , have you tried `minWidth: double.maxFinite`?

Here's a quick example,

```
ToggleSwitch(
  minWidth: double.maxFinite,
  initialLabelIndex: 0,
  totalSwitches: 3,
  labels: ['America', 'Canada', 'Mexico'],
  onToggle: (index) {
    print('switched to: $index');
  },
),
```
Portrait screenshot:
<img src="https://github.com/user-attachments/assets/32422c6d-15df-4bfd-92a9-9ecef1360d7d" width=40% height=40%>

Landscape screenshot:
<img src="https://github.com/user-attachments/assets/21cd3c9e-43d3-44d5-a678-a2854e69c68a" width=70% height=60%>
